
Verse.create(book_name:"Mathew", chapter_number:"5", verse_number:"6", verse:"Blessed are those who hunger and thirst for righteousness, For they shall be filled")
Verse.create(book_name:"Mathew", chapter_number:"5", verse_number:"8", verse:"Blessed are the pure in heart,For they shall see God.")
Verse.create(book_name:"Mathew", chapter_number:"5", verse_number:"12", verse:"Rejoice and be exceedingly glad, for great is your reward in heaven, for so they persecuted the prophets who were before you.")
Verse.create(book_name:"Mathew", chapter_number:"6", verse_number:"1", verse:"Take heed that you do not do your charitable deeds before men, to be seen by them. Otherwise you have no reward from your Father in heaven.")
Verse.create(book_name:"Mathew", chapter_number:"6", verse_number:"6", verse:"But you, when you pray, go into your room, and when you have shut your door, pray to your Father who is in the secret place; and your Father who sees in secret will reward you openly. ")
Verse.create(book_name:"Mathew", chapter_number:"6", verse_number:"22", verse:"The lamp of the body is the eye. If therefore your eye is good, your whole body will be full of light")
Verse.create(book_name:"Mathew", chapter_number:"7", verse_number:"6", verse:"o not give what is holy to the dogs; nor cast your pearls before swine, lest they trample them under their feet, and turn and tear you in pieces.")
Verse.create(book_name:"Mathew", chapter_number:"7", verse_number:"7", verse:"Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you")
Verse.create(book_name:"Mathew", chapter_number:"7", verse_number:"12", verse:"Therefore, whatever you want men to do to you, do also to them, for this is the Law and the Prophets.")